[package]
name = "p4ls"
version = "0.1.1"
edition = "2021"
description = "Extremely useful program"
license = "Apache-2.0"
authors = ["Dmitri Makarov <dmakarov@alumni.stanford.edu>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
